# Generated by Django 4.2.16 on 2026-04-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=30)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('term', models.CharField(default='Term 2, 2025/2026', max_length=50)),
                ('receipt_no', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Full Payment', 'Full Payment'), ('Tuition', 'Tuition'), ('Boarding', 'Boarding'), ('Development Levy', 'Development Levy'), ('Books & Stationery', 'Books & Stationery'), ('Miscellaneous', 'Miscellaneous')], default='Full Payment', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(help_text='e.g. JSS 1, SS 2', max_length=20)),
                ('session', models.CharField(default='2025/2026', max_length=20)),
                ('tuition', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('boarding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('development', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('books', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['class_level'],
                'unique_together': {('class_level', 'session')},
            },
        ),
    ]
