# Generated by Django 4.2.7 on 2026-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0004_alter_fees_session_term_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("pending", "Pending"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="term",
            field=models.CharField(
                db_index=True, default="Term 2, 2026", max_length=50
            ),
        ),
    ]
