# Generated by Django 4.2.16 on 2026-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_studentdocument_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="academichistory",
            name="division",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="academichistory",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("promotion", "Promotion"),
                    ("stream_change", "Stream Change"),
                    ("repetition", "Repetition"),
                    ("demotion", "Demotion"),
                ],
                default="promotion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="academichistory",
            name="new_class",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="academichistory",
            name="previous_class",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="academichistory",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="academichistory",
            name="average",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="academichistory",
            name="grade",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="academichistory",
            name="position",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student",
            name="academic_session",
            field=models.CharField(default="2026", max_length=20),
        ),
    ]
