# Generated by Django 4.2.7 on 2026-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_emergencycontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="fee_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("partial", "Partial"),
                    ("unpaid", "Unpaid"),
                ],
                db_index=True,
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("graduated", "Graduated"),
                    ("withdrawn", "Withdrawn"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
