# Generated by Django 4.2.7 on 2026-04-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_add_db_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=models.CharField(default="Tanzanian", max_length=100),
        ),
    ]
