# Generated by Django 4.2.30 on 2026-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_alter_student_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="disability_details",
            field=models.TextField(
                blank=True,
                help_text="Nature of the disability, support needs and any accommodations required",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="has_disability",
            field=models.BooleanField(default=False),
        ),
    ]
