# Generated by Django 4.2.30 on 2026-08-18 22:43

from django.db import migrations, models
import django.db.models.deletion


def mark_existing_guardians_as_primary(apps, schema_editor):
    """Every student had exactly one guardian before this — that one is the main contact."""
    ParentGuardian = apps.get_model("students", "ParentGuardian")
    ParentGuardian.objects.update(is_primary=True)


def unmark(apps, schema_editor):
    ParentGuardian = apps.get_model("students", "ParentGuardian")
    ParentGuardian.objects.update(is_primary=False)


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_student_disability_details_student_has_disability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentguardian",
            options={"ordering": ["-is_primary", "id"]},
        ),
        migrations.AddField(
            model_name="parentguardian",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="The main contact for this student. Shown first everywhere.",
            ),
        ),
        migrations.AlterField(
            model_name="parentguardian",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardians",
                to="students.student",
            ),
        ),
        migrations.RunPython(mark_existing_guardians_as_primary, unmark),
    ]
