# Generated by Django 4.2.16 on 2026-04-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked student (for parent role only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_accounts",
                to="students.student",
            ),
        ),
    ]
