# Generated by Django 4.2.7 on 2026-04-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_userprofile_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="grade_bands",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
