# Generated by Django 4.2.7 on 2026-04-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_grade_bands"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="notification_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="security_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
