# Generated by Django 4.2.16 on 2026-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolsettings",
            name="academic_session",
            field=models.CharField(default="2026", max_length=20),
        ),
    ]
