# Generated by Django 4.2.7 on 2026-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_ceomessage_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fundraiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("building", "Building & Infrastructure"),
                            ("education", "Education & Scholarships"),
                            ("orphans", "Orphan Support"),
                            ("equipment", "Equipment & Technology"),
                            ("emergency", "Emergency Relief"),
                            ("general", "General Fundraiser"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Full description of the fundraiser"),
                ),
                (
                    "short_desc",
                    models.CharField(
                        blank=True,
                        help_text="One-line summary shown on cards",
                        max_length=300,
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("donor_count", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="fundraisers/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on homepage / top of fundraisers page",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "donate_url",
                    models.URLField(
                        blank=True, help_text="External payment / donation link"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower = appears first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fundraiser",
                "verbose_name_plural": "Fundraisers",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
