# Generated by Django 4.2.16 on 2026-07-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='AL NAMAA ACADEMY', max_length=200)),
                ('hero_subtitle', models.CharField(default='Zanzibar • Expect Success', max_length=200)),
                ('hero_description', models.TextField(default='An officially accredited institution offering Nursery, Primary, and Secondary education — grounded in Islamic values, aligned with the ZEC Framework and NECTA examinations.')),
                ('hero_primary_cta', models.CharField(default='Apply for Admission', max_length=80)),
                ('hero_secondary_cta', models.CharField(default='Discover More', max_length=80)),
                ('about_title', models.CharField(default='Excellence Through Knowledge & Character', max_length=200)),
                ('about_description', models.TextField(default='Located in Kisauni, West “B” District, Zanzibar, AL NAMAA ACADEMY delivers high-quality education grounded in Islamic values. Our model combines rigorous academics with moral and spiritual development.')),
                ('about_highlights', models.JSONField(blank=True, default=list)),
                ('vision_title', models.CharField(default='Pathways to Fulfilment', max_length=200)),
                ('vision_description', models.TextField(default='To create pathways that assist every student in achieving their academic and personal goals — empowering them to build fulfilling futures and contribute meaningfully to the wider community.')),
                ('mission_title', models.CharField(default='Excellence in Education', max_length=200)),
                ('mission_description', models.TextField(default='To educate all students to the highest levels of achievement, preparing them to be productive, ethical, and creative members of society equipped with the knowledge, skills, and values needed for sustainable development.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_name',
            field=models.CharField(default='AL NAMAA ACADEMY', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='short_name',
            field=models.CharField(default='AL NAMAA', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'School Administrator'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('staff', 'Staff')], default='admin', max_length=20),
        ),
    ]
