# Generated by Django 4.2.30 on 2026-08-18 22:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_homepagecontent_featured_news_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="timetable_periods",
            field=models.JSONField(
                blank=True,
                default=core.models.default_timetable_periods,
                validators=[core.models.validate_timetable_periods],
            ),
        ),
    ]
