# Generated by Django 4.2.30 on 2026-08-18 23:21

import core.homepage_defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_schoolsettings_timetable_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="about_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_label",
            field=models.CharField(default="About Our School", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="about_paragraphs",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.about_paragraphs
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admission_levels",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.admission_levels
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_cta",
            field=models.CharField(default="Contact Admissions", max_length=100),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_description",
            field=models.TextField(
                default="Secure your child’s place at AL NAMAA ACADEMY. Applications are now being accepted for all three educational levels."
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_label",
            field=models.CharField(default="Enroll Now", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_title",
            field=models.CharField(
                default="Admissions Open for 2026/2027", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_area",
            field=models.CharField(
                default="Kisauni, West “B” District", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_hours",
            field=models.CharField(
                default="Monday – Friday · 8:00 AM – 4:00 PM", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_label",
            field=models.CharField(default="Our Campus", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_phones",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.contact_phones
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_region",
            field=models.CharField(default="Zanzibar, Tanzania", max_length=160),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_registration_line",
            field=models.CharField(
                default="Reg. No. P 10082026 • ZRB: Z052610299 • TIN: 175-002-324",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="credentials",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.credentials
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="features",
            field=models.JSONField(blank=True, default=core.homepage_defaults.features),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="features_badge_subtitle",
            field=models.CharField(
                default="Reg. No. P 10082026 • ZRB: Z052610299", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="features_badge_title",
            field=models.CharField(
                default="Ministry of Education & Vocational Training, Zanzibar",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="features_description",
            field=models.TextField(
                default="AL NAMAA ACADEMY stands apart through its unique integration of Islamic moral education with internationally-recognised academic standards."
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="features_label",
            field=models.CharField(default="Why Choose Us", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="features_title",
            field=models.CharField(
                default="Where Values Meet Academic Excellence", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_copyright",
            field=models.CharField(
                default="© 2026 AL NAMAA ACADEMY. All rights reserved.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_description",
            field=models.TextField(
                default="“Expect Success” — Officially recognised by the Ministry of Education and Vocational Training, Zanzibar. Delivering excellence through Islamic values."
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_established",
            field=models.CharField(
                default="Kisauni, Zanzibar • Est. 2020", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_registration_lines",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="gallery",
            field=models.JSONField(blank=True, default=core.homepage_defaults.gallery),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="gallery_label",
            field=models.CharField(default="Campus Life", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="gallery_title",
            field=models.CharField(default="Life at AL NAMAA", max_length=200),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_badge_text",
            field=models.CharField(default="Admissions · 2026 / 2027", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_stats",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.hero_stats
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="logo_upload",
            field=models.ImageField(blank=True, null=True, upload_to="homepage/logo/"),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="logo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="programs",
            field=models.JSONField(blank=True, default=core.homepage_defaults.programs),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="programs_label",
            field=models.CharField(default="Academic Programs", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="programs_title",
            field=models.CharField(
                default="Three Levels of Academic Excellence", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="purpose_label",
            field=models.CharField(default="Our Purpose", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="purpose_title",
            field=models.CharField(default="Vision & Mission", max_length=200),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="school_name",
            field=models.CharField(default="AL NAMAA ACADEMY", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="stats_banner",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.stats_banner
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="support_cta",
            field=models.CharField(
                default="Learn About Our Support Programs", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="support_description",
            field=models.TextField(
                default="Through the generosity of donors and partners under the Muzdalifa Community, 30% of our students receive 100% full sponsorship — ensuring no child is ever denied access to education because of financial hardship."
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="support_label",
            field=models.CharField(
                default="Inclusive Education & Sponsorship", max_length=140
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="support_stats",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.support_stats
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="support_title",
            field=models.CharField(
                default="Educating with Compassion, Building Every Child’s Future",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="tagline",
            field=models.CharField(default="Zanzibar • Expect Success", max_length=160),
        ),
    ]
