# Generated by Django 4.2.7 on 2026-04-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_studentdocument_file"),
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="students.student",
            ),
        ),
    ]
