# Generated by Django 4.2.16 on 2026-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0002_alter_payment_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="class_level",
            field=models.CharField(help_text="e.g. JSS 1, SS 2", max_length=50),
        ),
    ]
