# Generated by Django 4.2.16 on 2026-04-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0003_increase_class_level_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="session",
            field=models.CharField(default="2026", max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="term",
            field=models.CharField(default="Term 2, 2026", max_length=50),
        ),
    ]
