# Generated by Django 4.2.16 on 2026-04-07 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_academichistory_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=20)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Tanzanian', max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('applying_for_class', models.CharField(max_length=50)),
                ('student_type', models.CharField(choices=[('Day', 'Day'), ('Boarding', 'Boarding')], default='Day', max_length=10)),
                ('academic_session', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(max_length=30)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('parent_address', models.TextField(blank=True)),
                ('relationship', models.CharField(default='Parent', max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('interview_scheduled', 'Interview Scheduled'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('enrolled', 'Enrolled')], default='submitted', max_length=30)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.student')),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='admissions.admissionwindow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('marks', models.IntegerField(blank=True, help_text='Score out of 100', null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='admissions.applicant')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('other', 'Other')], default='cash', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='admissions.applicant')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
