# Generated by Django 4.2.16 on 2026-04-03 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_userprofile_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="student",
        ),
    ]
