# Generated by Django 4.2.7 on 2026-04-09 07:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_schoolsettings_academic_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("EXPORT", "Export"),
                    ("SETTINGS", "Settings"),
                    ("VIEW", "View"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="module",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="schoolsettings",
            name="grade_bands",
            field=models.JSONField(
                blank=True, default=list, validators=[core.models.validate_grade_bands]
            ),
        ),
    ]
