# Generated by Django 4.2.7 on 2026-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_db_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CEOMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(default="A Message from Our CEO", max_length=200),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The full letter/message text (HTML supported)"
                    ),
                ),
                ("author_name", models.CharField(default="", max_length=200)),
                (
                    "author_title",
                    models.CharField(default="Chief Executive Officer", max_length=200),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="team/ceo/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CEO Message",
                "verbose_name_plural": "CEO Messages",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Chief Executive Officer", max_length=150
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("leadership", "Leadership"),
                            ("academic", "Academic"),
                            ("administration", "Administration"),
                            ("support", "Support Staff"),
                            ("board", "Board of Directors"),
                        ],
                        default="academic",
                        max_length=30,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("linkedin_url", models.URLField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower = appears first"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "first_name"],
            },
        ),
    ]
