# Generated by Django 4.2.16 on 2026-08-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_homepagecontent_alter_schoolsettings_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
