# Generated by Django 4.2.16 on 2026-08-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_homepagecontent_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='featured_news_post',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/images/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_video_upload',
            field=models.FileField(blank=True, null=True, upload_to='homepage/videos/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_video_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/0t9kQG1Dqv0?rel=0&modestbranding=1&color=white'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='news_cards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='news_section_subtitle',
            field=models.CharField(default='Latest school stories, achievements and announcements', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='news_section_title',
            field=models.CharField(default='News & Updates', max_length=200),
        ),
    ]
