# Generated by Django 4.2.16 on 2026-08-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_homepagecontent_featured_news_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='academic_programs_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='academics_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='academics_section_subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='academics_section_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='accreditations_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='accreditations_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='accreditations_section_title',
            field=models.CharField(blank=True, default='Accreditations', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='achievements_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='achievements_section_title',
            field=models.CharField(blank=True, default='Our Achievements', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='admission_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='admission_timeline',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='admissions_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='admissions_section_subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='admissions_section_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='announcement_banner_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='announcement_banner_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='application_button_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='application_button_text',
            field=models.CharField(blank=True, default='Apply Now', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='awards_recognitions_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='campus_gallery_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='campus_gallery_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='current_application_window_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='display_contact_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='donation_call_to_action_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='donation_call_to_action_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='established_year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='events_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='events_section_title',
            field=models.CharField(blank=True, default='Upcoming Events', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='exam_performance_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='facilities_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='facilities_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='facilities_section_title',
            field=models.CharField(blank=True, default='Our Facilities', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='featured_fundraisers_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='featured_staff_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='featured_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='footer_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='footer_title',
            field=models.CharField(blank=True, default='Get In Touch', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='fundraising_section_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='fundraising_section_title',
            field=models.CharField(blank=True, default='Support Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='grade_levels_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_primary_cta_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_secondary_cta_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='homepage_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='leadership_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='leadership_section_title',
            field=models.CharField(blank=True, default='Our Leadership', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='link_to_full_calendar',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='maintenance_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='maintenance_mode_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='map_location_embed_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='news_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='news_max_display',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='office_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='og_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/og/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='principal_message_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='programs_overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='quick_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='school_story_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='school_story_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/images/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='school_story_section_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='school_story_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_cta_button_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_cta_button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_cta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_cta_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/cta/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_cta_section_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_cta_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='sections_display_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='share_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_beta_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_statistics_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='staff_directory_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='statistics_custom_label1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='statistics_custom_label2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='statistics_custom_value1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='statistics_custom_value2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='success_stories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='success_stories_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='tertiary_cta_button_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='tertiary_cta_button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='tertiary_cta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='tertiary_cta_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='tertiary_cta_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='testimonials_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='testimonials_section_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='testimonials_section_subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='testimonials_section_title',
            field=models.CharField(blank=True, default='What Our Community Says', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='total_teachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='university_placements_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='upcoming_events_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_us_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='why_choose_us_section_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
