# Generated by Django 4.2.30 on 2026-08-24 02:43

import core.homepage_defaults
from django.db import migrations, models

import core.homepage_defaults as hp


def fill_blank_collections(apps, schema_editor):
    """Give the existing row the content the page was hard-coding.

    Changing a field default only affects rows created afterwards, so the live
    record would keep its empty list and the editor would open on "no items" for
    blocks the public page is visibly rendering. Only untouched (empty) fields
    are filled, so nothing an administrator has already written is overwritten.
    """
    HomePageContent = apps.get_model("core", "HomePageContent")
    for row in HomePageContent.objects.all():
        changed = []
        if not row.about_images:
            row.about_images = hp.about_images()
            changed.append("about_images")
        if not row.news_cards:
            row.news_cards = hp.news_cards()
            changed.append("news_cards")
        if not row.featured_news_post:
            row.featured_news_post = hp.featured_news_post()
            changed.append("featured_news_post")
        if not row.footer_registration_lines:
            row.footer_registration_lines = hp.footer_registration_lines()
            changed.append("footer_registration_lines")
        if changed:
            row.save(update_fields=changed)


def unfill(apps, schema_editor):
    """Nothing to undo — the added fields go away with the schema."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_homepagecontent_academic_programs_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecontent",
            name="about_cta",
            field=models.CharField(default="Apply for Admission", max_length=100),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_status_apply_label",
            field=models.CharField(default="Apply Now", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_status_closed_label",
            field=models.CharField(default="CLOSED", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_status_closed_message",
            field=models.TextField(
                default="No application window is currently open. Check back later or contact the admissions office."
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_status_open_label",
            field=models.CharField(default="OPEN", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="admissions_status_title",
            field=models.CharField(default="Online Applications", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_form_button",
            field=models.CharField(default="Send Message", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_form_title",
            field=models.CharField(default="Send an Enquiry", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_heading",
            field=models.CharField(default="Get in Touch —", max_length=200),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_heading_highlight",
            field=models.CharField(default="We’re Here to Help", max_length=200),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_intro",
            field=models.TextField(
                default="Whether you’re a prospective parent, current student family, or community member, our team is ready to assist you with any enquiries about admissions, fees, or general information."
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="contact_section_label",
            field=models.CharField(default="Contact Us", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_contact_title",
            field=models.CharField(default="Contact", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_portal_links",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.footer_portal_links
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_portals_title",
            field=models.CharField(default="Portals", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_school_links",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.footer_school_links
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_school_links_title",
            field=models.CharField(default="School", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="footer_tagline",
            field=models.CharField(default="Expect Success", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_applications_closed_text",
            field=models.CharField(
                default="Applications Currently Closed", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_applications_open_text",
            field=models.CharField(
                default="Applications Open — Apply Now", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_scroll_label",
            field=models.CharField(default="Scroll", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_video_caption",
            field=models.CharField(
                default="Campus Tour — AL NAMAA ACADEMY", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="hero_video_thumbnail",
            field=models.URLField(
                blank=True,
                default="https://img.youtube.com/vi/0t9kQG1Dqv0/maxresdefault.jpg",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="mission_eyebrow",
            field=models.CharField(default="Mission", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="nav_apply_label",
            field=models.CharField(default="Apply Now", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="nav_links",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.nav_links
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="nav_login_label",
            field=models.CharField(default="Login", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="nav_results_label",
            field=models.CharField(default="Results", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="news_featured_badge",
            field=models.CharField(default="Featured", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="news_label",
            field=models.CharField(default="Latest", max_length=120),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="news_read_full_label",
            field=models.CharField(default="Read Full Story", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="news_read_more_label",
            field=models.CharField(default="Read More", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="vision_eyebrow",
            field=models.CharField(default="Vision", max_length=60),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="about_images",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.about_images
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="featured_news_post",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.featured_news_post
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="footer_registration_lines",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.footer_registration_lines
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="news_cards",
            field=models.JSONField(
                blank=True, default=core.homepage_defaults.news_cards
            ),
        ),
        migrations.RunPython(fill_blank_collections, unfill),
    ]
