# Generated by Django 4.2.16 on 2026-08-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_homepagecontent_academic_programs_count_and_more'),
        ('core', '0017_homepagecontent_about_images_and_more'),
    ]

    operations = [
    ]
