# Generated by Django 4.2.16 on 2026-08-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homepagecontent_about_cta_and_more'),
        ('core', '0018_merge_20260822_0248'),
    ]

    operations = [
    ]
