# Generated by Django 4.2.7 on 2026-04-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_studentdocument_file"),
        ("exams", "0002_remove_exam_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exammark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exam_marks",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exam_results",
                to="students.student",
            ),
        ),
    ]
