# Generated by Django 4.2.16 on 2026-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_add_teacher_comment_to_examresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="division",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Division I"),
                    ("II", "Division II"),
                    ("III", "Division III"),
                    ("IV", "Division IV"),
                    ("0", "Fail"),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="exammark",
            name="academic_session",
            field=models.CharField(default="2026", max_length=20),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="academic_session",
            field=models.CharField(default="2026", max_length=20),
        ),
    ]
