# Generated by Django 4.2.16 on 2026-04-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('academic_session', models.CharField(default='2025/2026', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('repeat', 'Repeat'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('student', 'term', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_score', models.DecimalField(decimal_places=2, help_text='Out of 30', max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, help_text='Out of 70', max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('position', models.IntegerField(default=0)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='exams.examresult')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('exam_result', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('exam_type', models.CharField(choices=[('CA 1', 'CA 1'), ('CA 2', 'CA 2'), ('Mid-Term', 'Mid-Term'), ('End of Term', 'End of Term')], max_length=20)),
                ('academic_session', models.CharField(default='2025/2026', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'ordering': ['student__last_name'],
                'unique_together': {('student', 'subject', 'term', 'exam_type', 'academic_session')},
            },
        ),
    ]
