# Generated by Django 4.2.7 on 2026-04-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exammark",
            name="exam_type",
            field=models.CharField(max_length=50),
        ),
    ]
