# Generated by Django 4.2.16 on 2026-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_alter_exammark_student_alter_examresult_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="teacher_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
