# Generated by Django 4.2.7 on 2026-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0005_examresult_division_alter_exammark_academic_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exammark",
            name="academic_session",
            field=models.CharField(db_index=True, default="2026", max_length=20),
        ),
        migrations.AlterField(
            model_name="exammark",
            name="term",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
