# Generated by Django 4.2.30 on 2026-08-24 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0006_add_db_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examresult",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_exam_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
