# Generated by Django 4.2.30 on 2026-08-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_examresult_released_at_examresult_released_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="fee_override",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examresult",
            name="fee_override_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
