# Generated by Django 4.2.7 on 2026-04-07 03:58

import django.core.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_parentguardian_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(
                help_text="Allowed: PDF, JPG, PNG, DOC, DOCX. Max size: 5MB",
                upload_to="student_documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png", "doc", "docx"]
                    ),
                    students.models.validate_file_size,
                    students.models.validate_file_name,
                ],
            ),
        ),
    ]
