# Generated by Django 4.2.7 on 2026-04-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="level",
            field=models.CharField(help_text="e.g. Std 1, Form 2", max_length=20),
        ),
        migrations.AlterField(
            model_name="class",
            name="section",
            field=models.CharField(max_length=50),
        ),
    ]
