# Generated by Django 4.2.7 on 2026-04-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_parentguardian_user"),
        ("academics", "0002_alter_class_level_alter_class_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("on_leave", "On Leave"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "teacher__name"],
                "unique_together": {("date", "teacher")},
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.student",
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_records",
                        to="academics.class",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "student__last_name", "student__first_name"],
                "unique_together": {("date", "student")},
            },
        ),
    ]
